# Generated by Django 4.1.6 on 2023-02-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=250)),
                ('teamimg', models.ImageField(upload_to='pics')),
                ('teamdesc', models.TextField()),
            ],
        ),
    ]
